Updates to all the generated files to add the --enable-CNL flag in configure
git-svn-id: http://svn.research.cc.gatech.edu/kaos/evpath/trunk@4986 8ba6a8b9-845b-0410-94f0-974be2f5df47

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -901,6 +901,8 @@ MATH_LIB
 CSH
 PATHPROG
 FFSDIR
+CNL_TRUE
+CNL_FALSE
 EVDIR
 LTLIBS
 DEMO_LIBS
@@ -1508,6 +1510,7 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-ltdl-install   install libltdl
+  --enable-CNL Enable a restricted socket only transport build to allow building on compute node linux. Default is disabled
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5318,13 +5321,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5321: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5324: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5324: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5327: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5327: output\"" >&5)
+  (eval echo "\"\$as_me:5330: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6545,7 +6548,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6548 "configure"' > conftest.$ac_ext
+  echo '#line 6551 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7921,11 +7924,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7924: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7927: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7928: \$? = $ac_status" >&5
+   echo "$as_me:7931: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8260,11 +8263,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8263: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8266: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8267: \$? = $ac_status" >&5
+   echo "$as_me:8270: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8365,11 +8368,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8368: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8371: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8372: \$? = $ac_status" >&5
+   echo "$as_me:8375: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8420,11 +8423,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8423: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8427: \$? = $ac_status" >&5
+   echo "$as_me:8430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11176,7 +11179,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11179 "configure"
+#line 11182 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11272,7 +11275,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11275 "configure"
+#line 11278 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12387,7 +12390,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12390 "configure"
+#line 12393 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14688,11 +14691,11 @@ fi
 
 search_list="$search_list /usr/include/ffs.h /usr/local/include/ffs.h /opt/ffs/include/ffs.h /opt/misc/include/ffs.h /opt/misc/include/$cercs_cv_archive/ffs.h"
 tmp_search_results=""
-echo "configure:14691: searching for $search_list " >&5
+echo "configure:14694: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:14695: first found $tmp_search_results " >&5
+	echo "configure:14698: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -14778,11 +14781,11 @@ fi
 
 search_list="$search_list /usr/lib/libffs.la /usr/local/lib/libffs.la /opt/ffs/lib/libffs.la /opt/misc/lib/libffs.la /opt/misc/lib/$cercs_cv_archive/libffs.la"
 tmp_search_results=""
-echo "configure:14781: searching for $search_list " >&5
+echo "configure:14784: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:14785: first found $tmp_search_results " >&5
+	echo "configure:14788: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -14851,11 +14854,11 @@ else
 
 search_list="$PWD/../ffs $PWD/../../ffs $PWD/../../../ffs"
 tmp_search_results=""
-echo "configure:14854: searching for $search_list " >&5
+echo "configure:14857: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:14858: first found $tmp_search_results " >&5
+	echo "configure:14861: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -14893,11 +14896,11 @@ else
 
 search_list="$PWD/../ffs $PWD/../../ffs $PWD/../../../ffs"
 tmp_search_results=""
-echo "configure:14896: searching for $search_list " >&5
+echo "configure:14899: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:14900: first found $tmp_search_results " >&5
+	echo "configure:14903: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15019,11 +15022,11 @@ fi
 
 search_list="$search_list /usr/include/gen_thread.h /usr/local/include/gen_thread.h /opt/gen_thread/include/gen_thread.h /opt/misc/include/gen_thread.h /opt/misc/include/$cercs_cv_archive/gen_thread.h"
 tmp_search_results=""
-echo "configure:15022: searching for $search_list " >&5
+echo "configure:15025: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15026: first found $tmp_search_results " >&5
+	echo "configure:15029: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15109,11 +15112,11 @@ fi
 
 search_list="$search_list /usr/lib/libgen_thread.la /usr/local/lib/libgen_thread.la /opt/gen_thread/lib/libgen_thread.la /opt/misc/lib/libgen_thread.la /opt/misc/lib/$cercs_cv_archive/libgen_thread.la"
 tmp_search_results=""
-echo "configure:15112: searching for $search_list " >&5
+echo "configure:15115: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15116: first found $tmp_search_results " >&5
+	echo "configure:15119: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15182,11 +15185,11 @@ else
 
 search_list="$PWD/../gen_thread $PWD/../../gen_thread $PWD/../../../gen_thread"
 tmp_search_results=""
-echo "configure:15185: searching for $search_list " >&5
+echo "configure:15188: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15189: first found $tmp_search_results " >&5
+	echo "configure:15192: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15224,11 +15227,11 @@ else
 
 search_list="$PWD/../gen_thread $PWD/../../gen_thread $PWD/../../../gen_thread"
 tmp_search_results=""
-echo "configure:15227: searching for $search_list " >&5
+echo "configure:15230: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15231: first found $tmp_search_results " >&5
+	echo "configure:15234: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15350,11 +15353,11 @@ fi
 
 search_list="$search_list /usr/include/cercs_env.h /usr/local/include/cercs_env.h /opt/cercs_env/include/cercs_env.h /opt/misc/include/cercs_env.h /opt/misc/include/$cercs_cv_archive/cercs_env.h"
 tmp_search_results=""
-echo "configure:15353: searching for $search_list " >&5
+echo "configure:15356: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15357: first found $tmp_search_results " >&5
+	echo "configure:15360: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15440,11 +15443,11 @@ fi
 
 search_list="$search_list /usr/lib/libcercs_env.la /usr/local/lib/libcercs_env.la /opt/cercs_env/lib/libcercs_env.la /opt/misc/lib/libcercs_env.la /opt/misc/lib/$cercs_cv_archive/libcercs_env.la"
 tmp_search_results=""
-echo "configure:15443: searching for $search_list " >&5
+echo "configure:15446: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15447: first found $tmp_search_results " >&5
+	echo "configure:15450: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15513,11 +15516,11 @@ else
 
 search_list="$PWD/../cercs_env $PWD/../../cercs_env $PWD/../../../cercs_env"
 tmp_search_results=""
-echo "configure:15516: searching for $search_list " >&5
+echo "configure:15519: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15520: first found $tmp_search_results " >&5
+	echo "configure:15523: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15555,11 +15558,11 @@ else
 
 search_list="$PWD/../cercs_env $PWD/../../cercs_env $PWD/../../../cercs_env"
 tmp_search_results=""
-echo "configure:15558: searching for $search_list " >&5
+echo "configure:15561: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15562: first found $tmp_search_results " >&5
+	echo "configure:15565: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15857,11 +15860,11 @@ fi
 
 search_list="$search_list /usr/include/atl.h /usr/local/include/atl.h /opt/atl/include/atl.h /opt/misc/include/atl.h /opt/misc/include/$cercs_cv_archive/atl.h"
 tmp_search_results=""
-echo "configure:15860: searching for $search_list " >&5
+echo "configure:15863: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15864: first found $tmp_search_results " >&5
+	echo "configure:15867: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -15947,11 +15950,11 @@ fi
 
 search_list="$search_list /usr/lib/libatl.la /usr/local/lib/libatl.la /opt/atl/lib/libatl.la /opt/misc/lib/libatl.la /opt/misc/lib/$cercs_cv_archive/libatl.la"
 tmp_search_results=""
-echo "configure:15950: searching for $search_list " >&5
+echo "configure:15953: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:15954: first found $tmp_search_results " >&5
+	echo "configure:15957: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -16020,11 +16023,11 @@ else
 
 search_list="$PWD/../atl $PWD/../../atl $PWD/../../../atl"
 tmp_search_results=""
-echo "configure:16023: searching for $search_list " >&5
+echo "configure:16026: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:16027: first found $tmp_search_results " >&5
+	echo "configure:16030: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -16062,11 +16065,11 @@ else
 
 search_list="$PWD/../atl $PWD/../../atl $PWD/../../../atl"
 tmp_search_results=""
-echo "configure:16065: searching for $search_list " >&5
+echo "configure:16068: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:16069: first found $tmp_search_results " >&5
+	echo "configure:16072: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -16111,6 +16114,38 @@ fi
 fi
 
 LTLIBS="$cercs_cv_atl_link_dir/libatl.la $LTLIBS"
+
+
+computenode=disable
+# Check whether --enable-computenode was given.
+if test "${enable_computenode+set}" = set; then
+  enableval=$enable_computenode;  if test "x$enableval" = "xtrue"; then
+		echo "Configuring for compute node linux"
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_DYNAMIC_LINKING 1
+_ACEOF
+
+		computenode=true
+	else
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_DYNAMIC_LINKING 0
+_ACEOF
+
+		computenode=false
+	fi
+fi
+
+
+ if test x$computenode = xtrue; then
+  CNL_TRUE=
+  CNL_FALSE='#'
+else
+  CNL_TRUE='#'
+  CNL_FALSE=
+fi
+
 
 
 
@@ -16483,6 +16518,13 @@ LT_CONFIG_H=config.h
     ltdl_LTLIBOBJS=$_ltdl_ltlibobjs
 
 
+if test -z "${CNL_TRUE}" && test -z "${CNL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CNL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CNL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -17451,6 +17493,8 @@ MATH_LIB!$MATH_LIB$ac_delim
 CSH!$CSH$ac_delim
 PATHPROG!$PATHPROG$ac_delim
 FFSDIR!$FFSDIR$ac_delim
+CNL_TRUE!$CNL_TRUE$ac_delim
+CNL_FALSE!$CNL_FALSE$ac_delim
 EVDIR!$EVDIR$ac_delim
 LTLIBS!$LTLIBS$ac_delim
 DEMO_LIBS!$DEMO_LIBS$ac_delim
@@ -17461,7 +17505,7 @@ ltdl_LIBOBJS!$ltdl_LIBOBJS$ac_delim
 ltdl_LTLIBOBJS!$ltdl_LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 46; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
